const updatedArray=[{
    name: "Write a program to print a message",
    language: "C",
    semester: 2,
    completed: true,
    difficulty: "easy",
    details: "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target. You may assume that each input would have exactly one solution, and you may not use the same element twice. You can return the answer in any order.",
    constraints: "2 <= nums.length <= 104\n-109 <= nums[i] <= 109\n-109 <= target <= 109",
    staterCode: "var twoSum = function(nums, target) {\n\n};",
  },
  {
    name: "Write a program to print the personal information",
    language: "C",
    semester: 2,
    completed: true,
    difficulty: "easy",
    details: "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target. You may assume that each input would have exactly one solution, and you may not use the same element twice. You can return the answer in any order.",
    constraints: "2 <= nums.length <= 104\n-109 <= nums[i] <= 109\n-109 <= target <= 109",
    staterCode: "var twoSum = function(nums, target) {\n\n};",
  }]
  const data = [
    {
      name: "Simple C++ Program",
      language: "C++",
      semester: 3,
      completed: false,
      difficulty: "easy",
    },
    {
      name: "Program on Data Types and Operators",
      language: "C++",
      semester: 3,
      completed: false,
      difficulty: "easy",
    },
    {
      name: "Program for Looping and Branching Statement",
      language: "C++",
      semester: 3,
      completed: false,
      difficulty: "easy",
    },
    {
      name: "Program for Reference Variable",
      language: "C++",
      semester: 3,
      completed: false,
      difficulty: "easy",
    },
    {
      name: "Program for Function Overloading",
      language: "C++",
      semester: 3,
      completed: false,
      difficulty: "easy",
    },
    {
      name: "Program for Friend Function and Inline Function",
      language: "C++",
      semester: 3,
      completed: false,
      difficulty: "medium",
    },
    {
      name: "Program for Static Data Member and Function",
      language: "C++",
      semester: 3,
      completed: false,
      difficulty: "medium",
    },
    {
      name: "Program for Operator Overloading",
      language: "C++",
      semester: 3,
      completed: false,
      difficulty: "medium",
    },
    {
      name: "Program for Inheritance",
      language: "C++",
      semester: 3,
      completed: false,
      difficulty: "medium",
    },
    {
      name: "Program for Virtual Function and Classes",
      language: "C++",
      semester: 3,
      completed: false,
      difficulty: "medium",
    },

    {
      name: "Write a program to print a message",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "easy",
      details: "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target. You may assume that each input would have exactly one solution, and you may not use the same element twice. You can return the answer in any order.",
      constraints: "2 <= nums.length <= 104\n-109 <= nums[i] <= 109\n-109 <= target <= 109",
      staterCode: "var twoSum = function(nums, target) {\n\n};",
    },
    {
      name: "Write a program to print the personal information",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "easy",
      details: "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target. You may assume that each input would have exactly one solution, and you may not use the same element twice. You can return the answer in any order.",
      constraints: "2 <= nums.length <= 104\n-109 <= nums[i] <= 109\n-109 <= target <= 109",
      staterCode: "var twoSum = function(nums, target) {\n\n};",
    },  {
      name: "Write a program to accept the personal information and print",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "easy",
    },
    {
      name: "Write a program for addition, subtraction, multiplication, and division",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to accept the marks of six subjects and calculate the percentage",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to print the table of a given number",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to find that entered number is even or odd",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "easy",
    },
    {
      name: "Write a program to print the even and odd numbers up to a given number",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to print the alphabets from a to z and z to a",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "easy",
    },
    {
      name: "Write a program to display the ASCII value of a to z alphabets",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "easy",
    },
    {
      name: "Write a program to find the prime number up to a given number",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to find that entered number is prime or not",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to print the Fibonacci series up to a given number",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to find the area and perimeter of Triangle & Rectangle",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to find the area of circle & square",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "easy",
    },
    {
      name: "Write a program to find positive and negative numbers using if...else statement",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "easy",
    },
    {
      name: "Write a program to print the days of the week & months of the year using switch statement",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to find whether the entered character is consonant or vowel using switch statement",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to find whether the entered year is a leap year or not using a ternary operator",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "easy",
    },
    {
      name: "Write a program to print the class or division using else...if ladder",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to find the greater number among two numbers using if...else statement",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "easy",
    },
    {
      name: "Write a program using goto and break statements",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "hard",
    },
    {
      name: "Write a program to find an Armstrong Number",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to print the numbers from 1 to 10 in ascending and descending order",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to print the addition of numbers from 1 to 10 using an array",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to print the addition of given 10 numbers using an array",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to print the 2 X 2 matrix",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to print the addition of 2 X 2 matrices",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to print the addition of 2 X 3 matrices",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to transpose matrices",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to multiply matrices",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to find an Armstrong number",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to find the factorial of a given number",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to print personal and professional information using structure and union",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Write a program to sort the array using bubble sort technique",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "hard",
    },
    {
      name: "Demonstrate string library functions",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Demonstrate recursion functions",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Demonstrate pointers",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Create a structure of employee & read records of five employees and display them",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Create a file student and store the records of ten students",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Demonstrate file handling",
      language: "C",
      semester: 2,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Program to demonstrate Constant Variable",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "easy",
    },
    {
      name: "Program to demonstrate scope of Variable",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "easy",
    },
    {
      name: "Program to demonstrate branching statement",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "easy",
    },
    {
      name: "Program to demonstrate Looping statement",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "easy",
    },
    {
      name: "Program to demonstrate simple class",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Program to demonstrate method parameter",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Program to demonstrate method overloading",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Program to demonstrate constructor",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Program to demonstrate static member",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Program to demonstrate Method overriding",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Program to demonstrate Final variable, Method and Final Class",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Program to demonstrate Finilize method",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Program to demonstrate Array and Its types",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Program to demonstrate String class and its methods",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Program to demonstrate StringBuffer and its methods",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Program to demonstrate inheritance and its types",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Program to demonstrate Abstract method and Abstract Class",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Program to demonstrate Multiple catch statement",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Program to demonstrate finally clause",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Program to demonstrate package",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Program to demonstrate interface",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Program to demonstrate Applet life cycle",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Program to demonstrate param tag",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "medium",
    },
    {
      name: "Program to demonstrate Graphics class",
      language: "Java",
      semester: 3,
      completed: true,
      difficulty: "medium",
    },
  ];